spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
        format_sql: true
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  datasource:
    url: jdbc:h2:mem:voting
#    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
# Absolute path
#    url: jdbc:h2:C:/projects/bootjava/restorant-voting/db/voting
#    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/restorant-voting/db/voting
# Relative path form current dir
#    url: jdbc:h2:./db/voting
# Relative path from home
#    url: jdbc:h2:~/voting
#    tcp: jdbc:h2:tcp://localhost:9092/~/voting
    username: sa
    password:
  h2:
    console:
      enabled: true